package com.xjtu.friendtrip.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xjtu.friendtrip.db.DBTrace;
import com.xjtu.friendtrip.db.DBTraceFile;

import com.xjtu.friendtrip.db.DBTraceDao;
import com.xjtu.friendtrip.db.DBTraceFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBTraceDaoConfig;
    private final DaoConfig dBTraceFileDaoConfig;

    private final DBTraceDao dBTraceDao;
    private final DBTraceFileDao dBTraceFileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBTraceDaoConfig = daoConfigMap.get(DBTraceDao.class).clone();
        dBTraceDaoConfig.initIdentityScope(type);

        dBTraceFileDaoConfig = daoConfigMap.get(DBTraceFileDao.class).clone();
        dBTraceFileDaoConfig.initIdentityScope(type);

        dBTraceDao = new DBTraceDao(dBTraceDaoConfig, this);
        dBTraceFileDao = new DBTraceFileDao(dBTraceFileDaoConfig, this);

        registerDao(DBTrace.class, dBTraceDao);
        registerDao(DBTraceFile.class, dBTraceFileDao);
    }
    
    public void clear() {
        dBTraceDaoConfig.getIdentityScope().clear();
        dBTraceFileDaoConfig.getIdentityScope().clear();
    }

    public DBTraceDao getDBTraceDao() {
        return dBTraceDao;
    }

    public DBTraceFileDao getDBTraceFileDao() {
        return dBTraceFileDao;
    }

}
